### ISSUE TITLE
All spans have the same kind

### ISSUE THREAD

**Issue by adigiorgi-clickup** [krakend/krakend-otel#5]
All spans produced by the KrakenD OTEL integration have the same default `INTERNAL` [SpanKind](https://opentelemetry.io/docs/specs/otel/trace/api/#spankind). In Datadog, the span kind is used to generate the "operation name" of the spans. With all the spans having the same kind, it means they also have all the same name:

<img width="492" alt="Screenshot 2024-03-15 at 4 42 04 PM" src="https://github.com/krakend/krakend-otel/assets/108835018/f6e3d843-28b9-49da-af91-7b5fb666ff86">

This is an issue when Datadog selects the [primary operation](https://docs.datadoghq.com/tracing/guide/configuring-primary-operation/) of a service, because it's not possible to distinguish between the entry-point span of a KrakenD HTTP request, and all the other spans.

![Screenshot 2024-03-14 at 10 09 55 PM](https://github.com/krakend/krakend-otel/assets/108835018/5c89222c-d898-428a-af20-4ebe18a3550f)

To be semantically accurate with the OTEL specifications, the entry-point span of a KrakenD trace should have kind equal to `SERVER`, and the spans corresponding to requests to backend services should have kind equal to `CLIENT`.

**Comment by thinkingabouther** [comment]
Hey, noticed the issue being closed, but the change is yet to be released; would appreciate it being included in a minor version bump, if possible, as the [OTEL Collector service graph](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/servicegraphconnector/README.md) relies on proper `span.kind` values as well.
Thank you for your efforts!
