### ISSUE TITLE
Paths skipped still generate metric values in form of http_route="404 Not Found"

### ISSUE THREAD

**Issue by rassmate** [krakend/krakend-otel#9]
Hi.

I'm evaluating krakend with opentelemetry and i really appreciate your work.
I noticed when starting the docker example in the repository that for the skipped paths (the default skipped paths) I still receive metrics with http_route="404 Not Found"

Is this by design?

**Comment by dhontecillas** [comment]
@rassmate , I will take a look and will update you about this issue. Thanks for reporting it.
